routes/web.php
<?php

//client side route.............................
Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/products/product_by/category/{id}', 'HomeController@showProductByCategoryId')->name('product_by_category_id');
Route::get('/products/product_by/manufacturer/{id}', 'HomeController@showProductByManufacturerId')->name('product_by_manufacturer_id');
Route::get('/products/product_details/{id}', 'HomeController@showProductDetailsByIds')->name('product_details');
Route::get('/products/product_details/{id}', 'HomeController@showProductDetailsById')->name('product_details');
Route::post('products/add_to/cart/{id}','cart\CartController@addToCart')->name('addToCart');

Route::get('products/show/cart','cart\CartController@showMyCart')->name('cart');


Route::get('products/remove/cart_item/{rowId}','cart\CartController@deleteCartItem')->name('cartdelete');
Route::post('products/update/item/{rowId}','cart\CartController@updateCartItem')->name('updateCart');
Route::get('products/show/shipping-address-for-checkout','checkout\CheckoutController@checkOut')->name('checkout');
Route::post('products/shipping/','shipping\ShippingController@saveShippingInformation')->name('saveShippingAddress');
Route::get('choose/payment-system','shipping\ShippingController@choosePaymentSystem')->name('choosePaymentSystem');
Route::post('payments/method-confirm','order\OrderHandellingController@paymentmehodHandelling')->name('paymentmethodConfirm');

//wishlist route....................
Route::get('products/add-to-wishlist/{id}','wishlist\WishlistController@addToWishlist')->name('addToWishlist');
Route::get('products/wish-list/{email}','wishlist\WishlistController@showMyWishlist')->name('mywishlist');

//cmpare list rout....................
Route::get('products/add-to-compare/{id}','compare\CompareController@addToCompare')->name('addToCompare');
Route::get('products/compare-list/{email}','compare\CompareController@showMyCompareList')->name('mycomparelist');
Route::get('remove-from-compae/{id}','compare\CompareController@removeFromCompare')->name('compareRemove');














//server side route.....................................


Route::prefix('admin')->group(function(){

		Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
		Route::post('/login', 'Admin\Auth\LoginController@login');
		Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');

		Route::get('/dashboard','Admin\AdminController@index');
		//category route....................
		Route::resource('/category','category\CategoryController');

		Route::get('/category/active/{catId}','category\CategoryController@activeCategory');
		Route::get('/category/deactive/{catId}','category\CategoryController@deactiveCategory');
		//manufacturer route.........
		Route::resource('/manufacturer','manufacturer\manufacturerController');
		Route::get('/manufacturer/active/{catId}','manufacturer\manufacturerController@activeManufacturer');
		Route::get('/manufacturer/deactive/{catId}','manufacturer\manufacturerController@deactiveManufacturer');

		//product route.......................................
		Route::resource('/product','product\ProductController');
		Route::get('product/active/{id}','product\ProductController@activeProduct');
		Route::get('product/deactive/{id}','product\ProductController@deactiveProduct');

		//slider Route................................................
		Route::resource('/slider','slider\SliderController');
		Route::get('slider/active/{id}','slider\SliderController@activeSlider');
		Route::get('slider/deactive/{id}','slider\SliderController@deactiveSlider');
		//ORder show.........................................
		Route::get('show-pending-order','order\OrderHandellingController@showAllPendingOrderToAdminPanel')->name('showPendingOrder');
		Route::get('show-success-order','order\OrderHandellingController@showAllSuccessOrderToAdminPanel')->name('showCompleteOrder');
		Route::get('order-details/{customer_name}/{shippingID}','order\OrderHandellingController@showDetailsOfOrder')->name('seeOrderDetails');
		Route::get('order/success/{id}','order\OrderHandellingController@orderSuccess');
		Route::get('order/pending/{id}','order\OrderHandellingController@orderPendig');
		
});

app/Http/Controllers/product/ProductController.php
<?php

namespace App\Http\Controllers\product;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\model\product\ProductModel;
use App\model\category\CatModel;
use App\model\manufacturer\ManufacturerModel;
use Session;
Session::start();

class ProductController extends Controller
{
    public function __construct()
    {
       $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $products = ProductModel::get();
       return view('product.productList')->with('products',$products);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = CatModel::get();
        $manufacturer = ManufacturerModel::get();
         return view('product.addProduct')->with(['categories' => $categories, 'manufactureres' => $manufacturer]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'productName' => 'required|string|max:30',
            'category_id' => 'required|integer',
            'manufacturer_id' => 'required|integer',
            'product_sd' => 'required',
            'product_ld' => 'required|min:30',
            'productImage' => 'required|mimes:jpeg,jpg,png,gif',
            'productPrice' => 'required',
            'productColor' => 'required|string',
            'productSize' => 'required|'
        ]);

        $image = $request->file('productImage');
        if($image){
            $imageName = str_random(20);
            $ext = strtolower($image->getClientOriginalExtension());
            $image_update_name = $imageName.'.'.$ext;
            $upload_path = 'image/';
            $image_url = $upload_path.$image_update_name;
            $succesImage = $image->move($upload_path,$image_update_name);
            if($succesImage){
                $input = [

                    'product_name' => $request->productName,
                    'category_id' => $request->category_id,
                    'manufacturer_id' => $request->manufacturer_id,
                    'product_sort_desc' => $request->product_sd,
                    'product_long_desc' => $request->product_ld,
                    'product_price' => $request->productPrice,
                    'product_size' => $request->productSize,
                    'product_color' => $request->productSize,
                    'product_status' =>$request->product_status,
                    'product_image' =>$image_url
                ];

                ProductModel::insert($input);
                return redirect(route('product.index'));
            }
        }

            $input = [

                    'product_name' => $request->productName,
                    'category_id' => $request->category_id,
                    'manufacturer_id' => $request->manufacturer_id,
                    'product_sort_desc' => $request->product_sd,
                    'product_long_desc' => $request->product_ld,
                    'product_price' => $request->productPrice,
                    'product_size' => $request->productSize,
                    'product_color' => $request->productSize,
                    'product_status' =>$request->product_status
                ];

                ProductModel::insert($input);
                return required(route('product.index'));
       

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $editProduct = ProductModel::where('id',$id)->get();
        $categories = CatModel::get();
        $manufactureres = ManufacturerModel::get();
        return view('product.productEdit')->with(['editProduct'=> $editProduct,'categories' => $categories, 'manufactureres' => $manufactureres]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            'productName' => 'required|string|max:30',
            'category_id' => 'required|integer',
            'manufacturer_id' => 'required|integer',
            'product_sd' => 'required',
            'product_ld' => 'required|min:30',
            'productImage' => 'mimes:jpeg,jpg,png,gif',
            'productPrice' => 'required',
            'productColor' => 'required|string',
            'productSize' => 'required|'
        ]);
        
        $image = $request->file('productImage');
        if($image){
            $imageName = str_random(20);
            $ext = strtolower($image->getClientOriginalExtension());
            $image_update_name = $imageName.'.'.$ext;
            $upload_path = 'image/';
            $image_url = $upload_path.$image_update_name;
            $succesImage = $image->move($upload_path,$image_update_name);
            if($succesImage){
                $input = [

                    'product_name' => $request->productName,
                    'category_id' => $request->category_id,
                    'manufacturer_id' => $request->manufacturer_id,
                    'product_sort_desc' => $request->product_sd,
                    'product_long_desc' => $request->product_ld,
                    'product_price' => $request->productPrice,
                    'product_size' => $request->productSize,
                    'product_color' => $request->productSize,
                    'product_status' =>$request->product_status,
                    'product_image' =>$image_url
                ];
               
                ProductModel::where('id',$id)->update($input);
                return redirect(route('product.index'));
            }
         }

            $input = [

                    'product_name' => $request->productName,
                    'category_id' => $request->category_id,
                    'manufacturer_id' => $request->manufacturer_id,
                    'product_sort_desc' => $request->product_sd,
                    'product_long_desc' => $request->product_ld,
                    'product_price' => $request->productPrice,
                    'product_size' => $request->productSize,
                    'product_color' => $request->productSize,
                    'product_status' =>$request->product_status
                ];
               
                ProductModel::where('id',$id)->update($input);
                return redirect(route('product.index'));
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        ProductModel::where('id',$id)->delete();
        Session::put('message','Product deleted');
        return redirect(route('product.index'));
    }


    public function activeProduct($id)
    {
        
        ProductModel::where('id',$id)->update(['product_status'=>0]);
        Session::put('message','Product acitvaded ');
        return redirect(route('product.index'));
    }


    public function deactiveProduct($id)
    {
        
        ProductModel::where('id',$id)->update(['product_status'=>1]);
        Session::put('message','Product deacitvaded ');
        return redirect(route('product.index'));
    }
}

resources/views/product/addProduct.blade.php
@extends('admin.adminlayouts')

@section('admin_maincontent')
				<div class="row-fluid sortable">
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon edit"></i><span class="break"></span>Form Elements</h2>


						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						
					<h1 class="center"> 
				         @if ($errors->any())
					          <div class="alert alert-info">
					              <ul>
					                  @foreach ($errors->all() as $error)
					                      <h3>{{ $error }}</h3>
					                  @endforeach
					              </ul>
					          </div>
					      @endif
					    
			        </h1>
			        <p class="alert-danger" style="text-align: center;">
					    @php
					    	$message = Session::get('error');
					    	if($message){

					    		echo $message;

					    		Session::put('error',NULL);
					    	}
					    @endphp
					</p>
						<form class="form-horizontal" method="post" action="{{  route('product.store') }}" enctype="multipart/form-data">
							@csrf
						  <fieldset>

							<div class="control-group">
							  <label class="control-label" for="productName">Product Name:</label>
							  <div class="controls">
								<input type="text" class="input-xlarge" name="productName" id="productName" placeholder="Write product Name here">
							  </div>
							</div>

							<div class="control-group">
								<label class="control-label" for="category_id" >Category</label>
								<div class="controls">
								  <select id="category_id" name="category_id">
								  	<option selected="selected">Select category</option>
								  	@foreach ($categories as $category)
									<option value="{{$category->id}}">{{$category->category_name}}</option>
								  		
								  	@endforeach

								  </select>
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="manufacturer_id">Manufacturer</label>
								<div class="controls">
								  <select id="manufacturer_id" name="manufacturer_id">
								  	<option selected="selected">Select manufacturer</option>
								  	@foreach ($manufactureres as $manufacturer)
								  		
									<option value="{{$manufacturer->id}}">{{$manufacturer->manufacturer_name}}</option>

								  	@endforeach

								  </select>
								</div>
							</div>


							<div class="control-group hidden-phone">
							  <label class="control-label" for="product_sd">Product Sort Desc</label>
							  <div class="controls">
								<textarea class="cleditor" id="product_sd" name="product_sd" rows="3"></textarea>
							  </div>
							</div>

							<div class="control-group hidden-phone">
							  <label class="control-label" for="product_ld">Product Long Desc</label>
							  <div class="controls">
								<textarea class="cleditor" id="product_ld" name="product_ld" rows="3"></textarea>
							  </div>
							</div>


							<div class="control-group">
							  <label class="control-label" for="productImage">Image</label>
							  <div class="controls">
								<input class="input-file uniform_on" name="productImage" id="productImage" type="file">
							  </div>
							</div>

							<div class="control-group">
							  <label class="control-label" for="productPrice">Price:</label>
							  <div class="controls">
								<input type="text" class="input-xlarge" name="productPrice" id="productPrice">
							  </div>
							</div>

							<div class="control-group">
							  <label class="control-label" for="productColor">Product Color:</label>
							  <div class="controls">
								<input type="text" class="input-xlarge" name="productColor" id="productColor" placeholder="Write product color here">
							  </div>
							</div>


							<div class="control-group">
							  <label class="control-label" for="productSize">Product Size:</label>
							  <div class="controls">
								<input type="text" class="input-xlarge" name="productSize" id="productSize" placeholder="Write product Size here">
							  </div>
							</div>

							<div class="control-group">
							  <label class="control-label" for="product_status">Product Status</label>
							  <div class="controls">
								<input type="checkbox" class="input-xlarge" name="product_status" id="product_status" value="1">status
							  </div>
							</div>

							<div class="form-actions">
							  <button type="submit" class="btn btn-primary">Save changes</button>
							  <button type="reset" class="btn">Cancel</button>
							</div>
						  </fieldset>
						</form>   

					</div>
				</div><!--/span-->

			</div><!--/row-->
@endsection

resources/views/product/productEdit.blade.php
@extends('admin.adminlayouts')

@section('admin_maincontent')
				<div class="row-fluid sortable">
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon edit"></i><span class="break"></span>Form Elements</h2>


						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						
					<h1 class="center"> 
				         @if ($errors->any())
					          <div class="alert alert-info">
					              <ul>
					                  @foreach ($errors->all() as $error)
					                      <h3>{{ $error }}</h3>
					                  @endforeach
					              </ul>
					          </div>
					      @endif
					    
			        </h1>
			        <p class="alert-danger" style="text-align: center;">
					    @php
					    	$message = Session::get('error');
					    	if($message){

					    		echo $message;

					    		Session::put('error',NULL);
					    	}
					    @endphp
					</p>
					@foreach ($editProduct as $product)
						
						<form class="form-horizontal" method="post" action="{{  route('product.update',$product->id) }}" enctype="multipart/form-data">
							@csrf
							@method('PUT')
						  <fieldset>

							<div class="control-group">
							  <label class="control-label" for="productName">Product Name:</label>
							  <div class="controls">
								<input type="text" class="input-xlarge" name="productName" id="productName" value="{{$product->product_name}}">
							  </div>
							</div>

							<div class="control-group">
								<label class="control-label" for="category_id" >Category</label>
								<div class="controls">
								  <select id="category_id" name="category_id">
								  	@foreach ($categories as $category)
									<option value="{{$category->id}}" 

											<?php if($category->id == $product->product_ld){  ?>
											selected
											<?php } ?>
										>{{$category->category_name}}</option>

								  		
								  	@endforeach

								  </select>
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="manufacturer_id">Manufacturer</label>
								<div class="controls">
								  <select id="manufacturer_id" name="manufacturer_id">
								  	@foreach ($manufactureres as $manufacturer)
								  		
									<option value="{{$manufacturer->id}}" 

										<?php if($manufacturer->id == $product->manufacturer_ld){  ?>
											selected
											<?php } ?>


										>{{$manufacturer->manufacturer_name}}</option>

								  	@endforeach

								  </select>
								</div>
							</div>


							<div class="control-group hidden-phone">
							  <label class="control-label" for="product_sd">Product Sort Desc</label>
							  <div class="controls">
								<textarea class="cleditor" id="product_sd" name="product_sd" rows="3">
									{{$product->product_sort_desc}}
								</textarea>
							  </div>
							</div>

							<div class="control-group hidden-phone">
							  <label class="control-label" for="product_ld">Product Long Desc</label>
							  <div class="controls">
								<textarea class="cleditor" id="product_ld" name="product_ld" rows="3">
									{{$product->product_long_desc}}
								</textarea>
							  </div>
							</div>


							<div class="control-group">
							  <label class="control-label" for="productImage">Image</label>
							  <div class="controls">
								<input class="input-file uniform_on" name="productImage" id="productImage" type="file">
							  </div>
							</div>

							<div class="control-group">
							  <label class="control-label" for="productImage">Previous Image</label>
							  <div class="controls">
								<img src="{{asset($product->product_image)}}" height="50px" width="100px">
							  </div>
							</div>

							<div class="control-group">
							  <label class="control-label" for="productPrice">Price:</label>
							  <div class="controls">
								<input type="text" class="input-xlarge" name="productPrice" id="productPrice" value="{{$product->product_price}}">
							  </div>
							</div>

							<div class="control-group">
							  <label class="control-label" for="productColor">Product Color:</label>
							  <div class="controls">
								<input type="text" class="input-xlarge" name="productColor" id="productColor" value="{{$product->product_color}}"">
							  </div>
							</div>


							<div class="control-group">
							  <label class="control-label" for="productSize">Product Size:</label>
							  <div class="controls">
								<input type="text" class="input-xlarge" name="productSize" id="productSize" value="{{$product->product_size}}">
							  </div>
							</div>
							<div class="form-actions">
							  <button type="submit" class="btn btn-primary">Save changes</button>
							  <button type="reset" class="btn">Cancel</button>
							</div>
						  </fieldset>
						</form>   
					@endforeach

					</div>
				</div><!--/span-->

			</div><!--/row-->
@endsection

resources/views/product/productList.blade.php
@extends('admin.adminlayouts')

@section('admin_maincontent')
							
			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="index.html">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
				<li><a href="#">Tables</a></li>
			</ul>

			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon user"></i><span class="break"></span>Members</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						<?php 
							$message = Session::get('message');
							if($message){
								echo "<p class='alert-info'>".$message."</p>";
								Session::put('message',NULL);
							}

						?>
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>ID</th>
								  <th>Product Name</th>
								  <th>Product Category</th>
								  <th>Product Manufacturer</th>
								  <th>Product Image</th>
								  <th>Product Price</th>
								  <th>Status</th>
								  <th>Actions</th>
							  </tr>
						  </thead>   
						  <tbody>
						  	@foreach($products as $product)
							<tr>
								<td>{{$product->id}}</td>
								<td>{{$product->product_name}}</td>
								<td>{{$product->category->category_name}}</td>
								<td>{{$product->manufacturer->manufacturer_name}}</td>
								<td><img src="{{asset($product->product_image)}}" height="50px" width="100px"></td>
								<td>{{$product->product_price}}</td>
								<td class="center">
									@if($product->product_status == 1)
										<a class="btn btn-danger" href="{{url('admin/product/active/'.$product->id)}}">
											<i class="halflings-icon white thumbs-down"></i>  
										</a>
									@else
										<a class="btn btn-success" href="{{url('admin/product/deactive/'.$product->id)}}">
											<i class="halflings-icon white thumbs-up"></i>  
										</a>
									@endif
								</td>
								<td class="center">
									<a class="btn btn-info" href="{{ route('product.edit',$product->id) }}">
										<i class="halflings-icon white edit"></i>  
									</a>
								
									<span>
										<form action="{{route('product.destroy',$product->id)}}" method="post" id="delete_form_{{$product->id}}" style="display: none">
					                      {{csrf_field()}}
					                      {{method_field('DELETE')}}
					                     </form>
					                     <a href="" onclick="

					                      if(confirm('Are sure to delete?'))
					                      {
					                        event.preventDefault();
					                        document.getElementById('delete_form_{{$product->id}}').submit();
					                      }
					                      else{
					                        event.preventDefault();
					                      }
					                     " class="btn btn-danger">
					                        <i class="halflings-icon white trash"></i> 
					                    </a>
									</span>
								</td>
							</tr>
						@endforeach
						  </tbody>
					  </table>            
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
@endsection