routes/web.php
<?php

//client side route.............................
Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/products/product_by/category/{id}', 'HomeController@showProductByCategoryId')->name('product_by_category_id');
Route::get('/products/product_by/manufacturer/{id}', 'HomeController@showProductByManufacturerId')->name('product_by_manufacturer_id');
Route::get('/products/product_details/{id}', 'HomeController@showProductDetailsByIds')->name('product_details');
Route::get('/products/product_details/{id}', 'HomeController@showProductDetailsById')->name('product_details');
Route::post('products/add_to/cart/{id}','cart\CartController@addToCart')->name('addToCart');

Route::get('products/show/cart','cart\CartController@showMyCart')->name('cart');


Route::get('products/remove/cart_item/{rowId}','cart\CartController@deleteCartItem')->name('cartdelete');
Route::post('products/update/item/{rowId}','cart\CartController@updateCartItem')->name('updateCart');
Route::get('products/show/shipping-address-for-checkout','checkout\CheckoutController@checkOut')->name('checkout');
Route::post('products/shipping/','shipping\ShippingController@saveShippingInformation')->name('saveShippingAddress');
Route::get('choose/payment-system','shipping\ShippingController@choosePaymentSystem')->name('choosePaymentSystem');
Route::post('payments/method-confirm','order\OrderHandellingController@paymentmehodHandelling')->name('paymentmethodConfirm');

//wishlist route....................
Route::get('products/add-to-wishlist/{id}','wishlist\WishlistController@addToWishlist')->name('addToWishlist');
Route::get('products/wish-list/{email}','wishlist\WishlistController@showMyWishlist')->name('mywishlist');

//cmpare list rout....................
Route::get('products/add-to-compare/{id}','compare\CompareController@addToCompare')->name('addToCompare');
Route::get('products/compare-list/{email}','compare\CompareController@showMyCompareList')->name('mycomparelist');
Route::get('remove-from-compae/{id}','compare\CompareController@removeFromCompare')->name('compareRemove');














//server side route.....................................


Route::prefix('admin')->group(function(){

		Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
		Route::post('/login', 'Admin\Auth\LoginController@login');
		Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');

		Route::get('/dashboard','Admin\AdminController@index');
		//category route....................
		Route::resource('/category','category\CategoryController');

		Route::get('/category/active/{catId}','category\CategoryController@activeCategory');
		Route::get('/category/deactive/{catId}','category\CategoryController@deactiveCategory');
		//manufacturer route.........
		Route::resource('/manufacturer','manufacturer\manufacturerController');
		Route::get('/manufacturer/active/{catId}','manufacturer\manufacturerController@activeManufacturer');
		Route::get('/manufacturer/deactive/{catId}','manufacturer\manufacturerController@deactiveManufacturer');

		//product route.......................................
		Route::resource('/product','product\ProductController');
		Route::get('product/active/{id}','product\ProductController@activeProduct');
		Route::get('product/deactive/{id}','product\ProductController@deactiveProduct');

		//slider Route................................................
		Route::resource('/slider','slider\SliderController');
		Route::get('slider/active/{id}','slider\SliderController@activeSlider');
		Route::get('slider/deactive/{id}','slider\SliderController@deactiveSlider');
		//ORder show.........................................
		Route::get('show-pending-order','order\OrderHandellingController@showAllPendingOrderToAdminPanel')->name('showPendingOrder');
		Route::get('show-success-order','order\OrderHandellingController@showAllSuccessOrderToAdminPanel')->name('showCompleteOrder');
		Route::get('order-details/{customer_name}/{shippingID}','order\OrderHandellingController@showDetailsOfOrder')->name('seeOrderDetails');
		Route::get('order/success/{id}','order\OrderHandellingController@orderSuccess');
		Route::get('order/pending/{id}','order\OrderHandellingController@orderPendig');
		
});

app/Http/Controllers/manufacturer/manufacturerController.php
<?php

namespace App\Http\Controllers\manufacturer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\model\manufacturer\ManufacturerModel;
use Session;
Session::start();

class manufacturerController extends Controller
{

    public function __construct()
    {
       $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $allManufacturer = ManufacturerModel::get();
        return view('manufacturer.manufacturerList')->with('manufacturers',$allManufacturer);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('manufacturer.addManufacturer');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
          $request->validate([

            'manufacturerNames' => 'required|string|max:30',
            'manufacturerDescription' =>'required'
         ]);

        $data = new ManufacturerModel();

        $data->manufacturer_name = $request->manufacturerNames;
        $data->manufacturer_description = $request->manufacturerDescription;
        
        $data->save();


        /*CatModel::create($catInput);*/
        return redirect(route('manufacturer.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $manufacturer = ManufacturerModel::where('id',$id)->get();
        return view('manufacturer.manufacturerEdit')->with('manufacturer',$manufacturer);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
          $request->validate([

            'manufacturerNames' => 'required|string|max:30',
            'manufacturerDescription' =>'required'
         ]);


        $manufacturerInput = [
            'manufacturer_name' =>$request->manufacturerNames,
            'manufacturer_description'=>$request->manufacturerDescription
        ];

        ManufacturerModel::where('manufacturer_id',$id)->update($manufacturerInput);
        return redirect(route('manufacturer.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        ManufacturerModel::where('id',$id)->delete();
        Session::put('message','category deleted');
        return redirect(route('manufacturer.index'));
    }

    public function activeManufacturer($id)
    {
        ManufacturerModel::where('id',$id)->update(['manufacturer_status'=>0]);
        Session::put('message','manufacturer status is changed');
        return redirect(route('manufacturer.index'));
    }

    public function deactiveManufacturer($id)
    {
        ManufacturerModel::where('id',$id)->update(['manufacturer_status'=>1]);
        Session::put('message','manufacturer status is changed');
        return redirect(route('manufacturer.index'));
    }
}

resources/views/manufacturer/addManufacturer.blade.php
@extends('admin.adminlayouts')

@section('admin_maincontent')
				<div class="row-fluid sortable">
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon edit"></i><span class="break"></span>Form Elements</h2>


						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						
					<h1 class="center"> 
				         @if ($errors->any())
					          <div class="alert alert-info">
					              <ul>
					                  @foreach ($errors->all() as $error)
					                      <h3>{{ $error }}</h3>
					                  @endforeach
					              </ul>
					          </div>
					      @endif
					    
			        </h1>
			        <p class="alert-danger" style="text-align: center;">
					    @php
					    	$message = Session::get('error');
					    	if($message){

					    		echo $message;

					    		Session::put('error',NULL);
					    	}
					    @endphp
					</p>
						<form class="form-horizontal" method="post" action="{{  route('manufacturer.store') }}">
							@csrf
						  <fieldset>

							<div class="control-group">
							  <label class="control-label" for="catName">Category Name:</label>
							  <div class="controls">
								<input type="text" class="input-xlarge" name="manufacturerNames" id="catName" placeholder="Write category Name here">
							  </div>
							</div>

							<div class="control-group hidden-phone">
							  <label class="control-label" for="textarea2">Description</label>
							  <div class="controls">
								<textarea class="cleditor" name="manufacturerDescription" id="textarea2" rows="3"></textarea>
							  </div>
							</div>

							<div class="control-group">
							  <label class="control-label" for="status">Status:</label>
							  <div class="controls">
								<input type="checkbox" class="input-xlarge" name="status" id="status" value="1">status
							  </div>
							</div>

							<div class="form-actions">
							  <button type="submit" class="btn btn-primary">Save</button>
							  <button type="reset" class="btn">Cancel</button>
							</div>
						  </fieldset>
						</form>   

					</div>
				</div><!--/span-->

			</div><!--/row-->
@endsection

resources/views/manufacturer/manufacturerEdit.blade.php
@extends('admin.adminlayouts')

@section('admin_maincontent')
				<div class="row-fluid sortable">
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon edit"></i><span class="break"></span>Form Elements</h2>


						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						
					<h1 class="center"> 
				         @if ($errors->any())
					          <div class="alert alert-info">
					              <ul>
					                  @foreach ($errors->all() as $error)
					                      <h3>{{ $error }}</h3>
					                  @endforeach
					              </ul>
					          </div>
					      @endif
					    
			        </h1>
			        <p class="alert-danger" style="text-align: center;">
					    @php
					    	$message = Session::get('error');
					    	if($message){

					    		echo $message;

					    		Session::put('error',NULL);
					    	}
					    @endphp
					</p>


					@foreach ($manufacturer as $singleManufactuer)
						
					

						<form class="form-horizontal" method="post" action="{{  route('manufacturer.update',$singleManufactuer->id) }}">
							@csrf
							@method('PUT')
						  <fieldset>

							<div class="control-group">
							  <label class="control-label" for="catName">Category Name:</label>
							  <div class="controls">
								<input type="text" class="input-xlarge" name="manufacturerNames" id="catName" value="{{$singleManufactuer->manufacturer_name}}">
							  </div>
							</div>

							<div class="control-group hidden-phone">
							  <label class="control-label" for="textarea2">Description</label>
							  <div class="controls">
								<textarea class="cleditor" name="manufacturerDescription" id="textarea2" rows="3">{{$singleManufactuer->manufacturer_description}}</textarea>
							  </div>
							</div>

							<div class="form-actions">
							  <button type="submit" class="btn btn-primary">Save changes</button>
							  <a href="{{ route('manufacturer.index') }}" class="btn btn-primary">Back</a>
							</div>
						  </fieldset>
						</form>   
						@endforeach

					</div>
				</div><!--/span-->

			</div><!--/row-->
@endsection

resources/views/manufacturer/manufacturerList.blade.php
@extends('admin.adminlayouts')

@section('admin_maincontent')
							
			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="index.html">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
				<li><a href="#">Tables</a></li>
			</ul>

			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon user"></i><span class="break"></span>Members</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						<?php 
							$message = Session::get('message');
							if($message){
								echo "<p class='alert-info'>".$message."</p>";
								Session::put('message',NULL);
							}

						?>
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>ID</th>
								  <th>Category Name</th>
								  <th>Category Description</th>
								  <th>Status</th>
								  <th>Actions</th>
							  </tr>
						  </thead>   
						  <tbody>
						  	@foreach($manufacturers as $manufacturer)
							<tr>
								<td>{{$manufacturer->id}}</td>
								<td>{{$manufacturer->manufacturer_name}}</td>
								<td>{{$manufacturer->manufacturer_description}}</td>
								<td class="center">
									@if($manufacturer->manufacturer_status ==1)
										<span class="label label-success">Active</span>
									@else
										<span class="label label-danger">Deactive</span>
									@endif
								</td>
								<td class="center">
									@if($manufacturer->manufacturer_status == 1)
										<a class="btn btn-danger" href="{{url('admin/manufacturer/active/'.$manufacturer->id)}}">
											<i class="halflings-icon white thumbs-down"></i>  
										</a>
									@else
										<a class="btn btn-success" href="{{url('admin/manufacturer/deactive/'.$manufacturer->id)}}">
											<i class="halflings-icon white thumbs-up"></i>  
										</a>
									@endif
									<a class="btn btn-info" href="{{ route('manufacturer.edit',$manufacturer->id) }}">
										<i class="halflings-icon white edit"></i>  
									</a>
									<span>
										<form action="{{route('manufacturer.destroy',$manufacturer->id)}}" method="post" id="delete_form_{{$manufacturer->id}}" style="display: none">
					                      {{csrf_field()}}
					                      {{method_field('DELETE')}}
					                     </form>
					                     <a href="" onclick="

					                      if(confirm('Are sure to delete?'))
					                      {
					                        event.preventDefault();
					                        document.getElementById('delete_form_{{$manufacturer->id}}').submit();
					                      }
					                      else{
					                        event.preventDefault();
					                      }
					                     " class="btn btn-danger">
					                        <i class="halflings-icon white trash"></i> 
					                    </a>
									</span>
								</td>
							</tr>
						@endforeach
						  </tbody>
					  </table>            
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
@endsection